export const addresses = [
  {
    id: 1,
    street: "Anzinger",
    number: "51",
    city: "Huntsville",
    district: "Elka",
    state: "AL",
  },
  {
    id: 2,
    street: "Fremont",
    number: "2",
    city: "Denver",
    district: "Carioca",
    state: "CO",
  },
  {
    id: 3,
    street: "Roxbury",
    number: "34",
    city: "El Paso",
    district: "Lighthouse Bay",
    state: "TX",
  },
  {
    id: 4,
    street: "Stone Corner",
    number: "81",
    city: "Lubbock",
    district: "Florence",
    state: "TX",
  },
  {
    id: 5,
    street: "Chive",
    number: "046",
    city: "Saginaw",
    district: "East",
    state: "MI",
  },
  {
    id: 6,
    street: "Hallows",
    number: "09",
    city: "Shawnee Mission",
    district: "Eastlawn",
    state: "KS",
  },
  {
    id: 7,
    street: "Loeprich",
    number: "3589",
    city: "Paterson",
    district: "Tomscot",
    state: "NJ",
  },
  {
    id: 8,
    street: "Dawn",
    number: "523",
    city: "Fresno",
    district: "Nancy",
    state: "CA",
  },
  {
    id: 9,
    street: "Arapahoe",
    number: "72",
    city: "Denver",
    district: "Saint Paul",
    state: "CO",
  },
  {
    id: 10,
    street: "Hallows",
    number: "1117",
    city: "Longview",
    district: "Huxley",
    state: "TX",
  },
  {
    id: 11,
    street: "Granby",
    number: "68470",
    city: "Reno",
    district: "Toban",
    state: "NV",
  },
  {
    id: 12,
    street: "Dovetail",
    number: "48",
    city: "Madison",
    district: "Laurel",
    state: "WI",
  },
  {
    id: 13,
    street: "Surrey",
    number: "1019",
    city: "Boise",
    district: "Spenser",
    state: "ID",
  },
  {
    id: 14,
    street: "Dovetail",
    number: "20",
    city: "Saint Paul",
    district: "Del Mar",
    state: "MN",
  },
  {
    id: 15,
    street: "Morning",
    number: "34",
    city: "Little Rock",
    district: "Vidon",
    state: "AR",
  },
  {
    id: 16,
    street: "Tony",
    number: "77",
    city: "Dallas",
    district: "Ilene",
    state: "TX",
  },
  {
    id: 17,
    street: "Carioca",
    number: "540",
    city: "Bethesda",
    district: "Oneill",
    state: "MD",
  },
  {
    id: 18,
    street: "Hollow Ridge",
    number: "104",
    city: "Carlsbad",
    district: "Linden",
    state: "CA",
  },
  {
    id: 19,
    street: "Bellgrove",
    number: "96710",
    city: "Stamford",
    district: "Arkansas",
    state: "CT",
  },
  {
    id: 20,
    street: "Monterey",
    number: "642",
    city: "Lake Charles",
    district: "Scott",
    state: "LA",
  },
  {
    id: 21,
    street: "Crowley",
    number: "93133",
    city: "San Francisco",
    district: "Cascade",
    state: "CA",
  },
  {
    id: 22,
    street: "Russell",
    number: "5141",
    city: "Sacramento",
    district: "Riverside",
    state: "CA",
  },
  {
    id: 23,
    street: "Esker",
    number: "42",
    city: "Spokane",
    district: "Grim",
    state: "WA",
  },
  {
    id: 24,
    street: "Chinook",
    number: "4659",
    city: "Amarillo",
    district: "Katie",
    state: "TX",
  },
  {
    id: 25,
    street: "Summerview",
    number: "42763",
    city: "San Bernardino",
    district: "Scofield",
    state: "CA",
  },
  {
    id: 26,
    street: "Alpine",
    number: "78",
    city: "Des Moines",
    district: "Mendota",
    state: "IA",
  },
  {
    id: 27,
    street: "Di Loreto",
    number: "08163",
    city: "Bethesda",
    district: "Elgar",
    state: "MD",
  },
  {
    id: 28,
    street: "Heffernan",
    number: "5316",
    city: "Nashville",
    district: "Butternut",
    state: "TN",
  },
  {
    id: 29,
    street: "Clarendon",
    number: "44559",
    city: "Glendale",
    district: "Sheridan",
    state: "AZ",
  },
  {
    id: 30,
    street: "Hermina",
    number: "861",
    city: "Las Vegas",
    district: "Carberry",
    state: "NV",
  },
  {
    id: 31,
    street: "Maple Wood",
    number: "6914",
    city: "Portland",
    district: "Sunfield",
    state: "OR",
  },
  {
    id: 32,
    street: "School",
    number: "37978",
    city: "Boston",
    district: "Bobwhite",
    state: "MA",
  },
  {
    id: 33,
    street: "Merchant",
    number: "00",
    city: "Long Beach",
    district: "Towne",
    state: "CA",
  },
  {
    id: 34,
    street: "Vahlen",
    number: "7",
    city: "Washington",
    district: "Mesta",
    state: "DC",
  },
  {
    id: 35,
    street: "Straubel",
    number: "66052",
    city: "Toledo",
    district: "Arapahoe",
    state: "OH",
  },
  {
    id: 36,
    street: "Dahle",
    number: "09",
    city: "Boston",
    district: "Milwaukee",
    state: "MA",
  },
  {
    id: 37,
    street: "Green",
    number: "7",
    city: "Beaumont",
    district: "Parkside",
    state: "TX",
  },
  {
    id: 38,
    street: "Village",
    number: "0",
    city: "Pueblo",
    district: "Straubel",
    state: "CO",
  },
  {
    id: 39,
    street: "Troy",
    number: "55",
    city: "Bridgeport",
    district: "Esch",
    state: "CT",
  },
  {
    id: 40,
    street: "Lawn",
    number: "8417",
    city: "Memphis",
    district: "Spohn",
    state: "TN",
  },
  {
    id: 41,
    street: "Doe Crossing",
    number: "6800",
    city: "Montgomery",
    district: "Center",
    state: "AL",
  },
  {
    id: 42,
    street: "Colorado",
    number: "21",
    city: "Boston",
    district: "Ruskin",
    state: "MA",
  },
  {
    id: 43,
    street: "Tony",
    number: "62",
    city: "Kansas City",
    district: "Duke",
    state: "MO",
  },
  {
    id: 44,
    street: "Messerschmidt",
    number: "8338",
    city: "Stockton",
    district: "Orin",
    state: "CA",
  },
  {
    id: 45,
    street: "Longview",
    number: "82271",
    city: "Cedar Rapids",
    district: "Barby",
    state: "IA",
  },
  {
    id: 46,
    street: "Arrowood",
    number: "37",
    city: "Seattle",
    district: "Eliot",
    state: "WA",
  },
  {
    id: 47,
    street: "Forest",
    number: "0506",
    city: "Monroe",
    district: "Hoard",
    state: "LA",
  },
  {
    id: 48,
    street: "Mcbride",
    number: "8",
    city: "New York City",
    district: "Florence",
    state: "NY",
  },
  {
    id: 49,
    street: "Sachs",
    number: "44069",
    city: "Lawrenceville",
    district: "Oak Valley",
    state: "GA",
  },
  {
    id: 50,
    street: "Buena Vista",
    number: "3239",
    city: "Columbus",
    district: "Iowa",
    state: "OH",
  },
  {
    id: 51,
    street: "Di Loreto",
    number: "5",
    city: "Durham",
    district: "Acker",
    state: "NC",
  },
  {
    id: 52,
    street: "Sutherland",
    number: "70",
    city: "Dallas",
    district: "Haas",
    state: "TX",
  },
  {
    id: 53,
    street: "Darwin",
    number: "538",
    city: "Toledo",
    district: "International",
    state: "OH",
  },
  {
    id: 54,
    street: "Menomonie",
    number: "02602",
    city: "Wilmington",
    district: "Schurz",
    state: "DE",
  },
  {
    id: 55,
    street: "Hauk",
    number: "20265",
    city: "Macon",
    district: "Fisk",
    state: "GA",
  },
  {
    id: 56,
    street: "East",
    number: "0542",
    city: "Saint Paul",
    district: "Erie",
    state: "MN",
  },
  {
    id: 57,
    street: "Michigan",
    number: "51",
    city: "Washington",
    district: "Arizona",
    state: "DC",
  },
  {
    id: 58,
    street: "Shopko",
    number: "7",
    city: "El Paso",
    district: "Cottonwood",
    state: "TX",
  },
  {
    id: 59,
    street: "Arizona",
    number: "78",
    city: "Des Moines",
    district: "Rockefeller",
    state: "IA",
  },
  {
    id: 60,
    street: "Riverside",
    number: "25129",
    city: "Montgomery",
    district: "Drewry",
    state: "AL",
  },
  {
    id: 61,
    street: "Clemons",
    number: "24",
    city: "Richmond",
    district: "Ridgeview",
    state: "VA",
  },
  {
    id: 62,
    street: "Northwestern",
    number: "54",
    city: "Toledo",
    district: "Shasta",
    state: "OH",
  },
  {
    id: 63,
    street: "Caliangt",
    number: "676",
    city: "Omaha",
    district: "5th",
    state: "NE",
  },
  {
    id: 64,
    street: "Pine View",
    number: "41",
    city: "Hicksville",
    district: "Westerfield",
    state: "NY",
  },
  {
    id: 65,
    street: "Lyons",
    number: "36",
    city: "Knoxville",
    district: "Ramsey",
    state: "TN",
  },
  {
    id: 66,
    street: "Veith",
    number: "929",
    city: "Ocala",
    district: "Manley",
    state: "FL",
  },
  {
    id: 67,
    street: "Debra",
    number: "37",
    city: "Spokane",
    district: "Dovetail",
    state: "WA",
  },
  {
    id: 68,
    street: "Reindahl",
    number: "94548",
    city: "Pittsburgh",
    district: "Tennyson",
    state: "PA",
  },
  {
    id: 69,
    street: "Victoria",
    number: "46511",
    city: "San Diego",
    district: "Hallows",
    state: "CA",
  },
  {
    id: 70,
    street: "Alpine",
    number: "85",
    city: "Migrate",
    district: "Hagan",
    state: "KY",
  },
  {
    id: 71,
    street: "Nova",
    number: "053",
    city: "Springfield",
    district: "Linden",
    state: "MA",
  },
  {
    id: 72,
    street: "Northfield",
    number: "59652",
    city: "Las Cruces",
    district: "Utah",
    state: "NM",
  },
  {
    id: 73,
    street: "Milwaukee",
    number: "4",
    city: "Indianapolis",
    district: "Bunting",
    state: "IN",
  },
  {
    id: 74,
    street: "Nancy",
    number: "42",
    city: "Decatur",
    district: "Upham",
    state: "IL",
  },
  {
    id: 75,
    street: "Corscot",
    number: "73172",
    city: "Laredo",
    district: "Anderson",
    state: "TX",
  },
  {
    id: 76,
    street: "Pawling",
    number: "0",
    city: "Shawnee Mission",
    district: "Susan",
    state: "KS",
  },
  {
    id: 77,
    street: "Sutherland",
    number: "616",
    city: "Birmingham",
    district: "Sundown",
    state: "AL",
  },
  {
    id: 78,
    street: "Dawn",
    number: "41",
    city: "Charleston",
    district: "Merry",
    state: "WV",
  },
  {
    id: 79,
    street: "Anderson",
    number: "6597",
    city: "Greenville",
    district: "Bellgrove",
    state: "SC",
  },
  {
    id: 80,
    street: "Rusk",
    number: "87087",
    city: "Hialeah",
    district: "Killdeer",
    state: "FL",
  },
  {
    id: 81,
    street: "Burrows",
    number: "54777",
    city: "Waco",
    district: "Fordem",
    state: "TX",
  },
  {
    id: 82,
    street: "West",
    number: "348",
    city: "Columbus",
    district: "Ramsey",
    state: "GA",
  },
  {
    id: 83,
    street: "Mitchell",
    number: "718",
    city: "Burbank",
    district: "Caliangt",
    state: "CA",
  },
  {
    id: 84,
    street: "Towne",
    number: "7253",
    city: "Arlington",
    district: "Petterle",
    state: "TX",
  },
  {
    id: 85,
    street: "Calypso",
    number: "5932",
    city: "Garland",
    district: "Ilene",
    state: "TX",
  },
  {
    id: 86,
    street: "Paget",
    number: "8755",
    city: "Washington",
    district: "Larry",
    state: "DC",
  },
  {
    id: 87,
    street: "Hayes",
    number: "48",
    city: "Stockton",
    district: "Victoria",
    state: "CA",
  },
  {
    id: 88,
    street: "Bunting",
    number: "05860",
    city: "Mobile",
    district: "Marcy",
    state: "AL",
  },
  {
    id: 89,
    street: "Bluejay",
    number: "2",
    city: "Huntington",
    district: "Park Meadow",
    state: "WV",
  },
  {
    id: 90,
    street: "Rowland",
    number: "6",
    city: "Van Nuys",
    district: "Amoth",
    state: "CA",
  },
  {
    id: 91,
    street: "Eastwood",
    number: "4",
    city: "Canton",
    district: "Bunting",
    state: "OH",
  },
  {
    id: 92,
    street: "Swallow",
    number: "138",
    city: "Colorado Springs",
    district: "Sunnyside",
    state: "CO",
  },
  {
    id: 93,
    street: "Orin",
    number: "1",
    city: "Harrisburg",
    district: "Welch",
    state: "PA",
  },
  {
    id: 94,
    street: "Fieldstone",
    number: "71767",
    city: "Buffalo",
    district: "Calypso",
    state: "NY",
  },
  {
    id: 95,
    street: "Sycamore",
    number: "2",
    city: "Sacramento",
    district: "Russell",
    state: "CA",
  },
  {
    id: 96,
    street: "Fordem",
    number: "37346",
    city: "Stamford",
    district: "Paget",
    state: "CT",
  },
  {
    id: 97,
    street: "Nancy",
    number: "3499",
    city: "Atlanta",
    district: "Oak",
    state: "GA",
  },
  {
    id: 98,
    street: "Valley Edge",
    number: "9902",
    city: "Washington",
    district: "Forest Dale",
    state: "DC",
  },
  {
    id: 99,
    street: "Anniversary",
    number: "303",
    city: "Fresno",
    district: "Summit",
    state: "CA",
  },
  {
    id: 100,
    street: "Aberg",
    number: "69",
    city: "Cincinnati",
    district: "Vera",
    state: "OH",
  },
  {
    id: 101,
    street: "Katie",
    number: "5329",
    city: "Milwaukee",
    district: "Hollow Ridge",
    state: "WI",
  },
  {
    id: 102,
    street: "Anderson",
    number: "86",
    city: "White Plains",
    district: "Shelley",
    state: "NY",
  },
  {
    id: 103,
    street: "Bobwhite",
    number: "23396",
    city: "San Jose",
    district: "David",
    state: "CA",
  },
  {
    id: 104,
    street: "Moulton",
    number: "4914",
    city: "Fort Myers",
    district: "Manitowish",
    state: "FL",
  },
  {
    id: 105,
    street: "Michigan",
    number: "7",
    city: "Charlotte",
    district: "Bashford",
    state: "NC",
  },
  {
    id: 106,
    street: "Autumn Leaf",
    number: "4",
    city: "Evansville",
    district: "Ridge Oak",
    state: "IN",
  },
  {
    id: 107,
    street: "Forest",
    number: "29953",
    city: "Salt Lake City",
    district: "Kinsman",
    state: "UT",
  },
  {
    id: 108,
    street: "Buell",
    number: "38813",
    city: "Anaheim",
    district: "Mallard",
    state: "CA",
  },
  {
    id: 109,
    street: "Goodland",
    number: "265",
    city: "Cleveland",
    district: "Bayside",
    state: "OH",
  },
  {
    id: 110,
    street: "Elka",
    number: "87",
    city: "Newark",
    district: "Roth",
    state: "NJ",
  },
  {
    id: 111,
    street: "Lunder",
    number: "188",
    city: "Buffalo",
    district: "Pine View",
    state: "NY",
  },
  {
    id: 112,
    street: "Linden",
    number: "38",
    city: "Corona",
    district: "Troy",
    state: "CA",
  },
  {
    id: 113,
    street: "Bluestem",
    number: "67274",
    city: "San Luis Obispo",
    district: "Granby",
    state: "CA",
  },
  {
    id: 114,
    street: "Onsgard",
    number: "36950",
    city: "Richmond",
    district: "Bultman",
    state: "VA",
  },
  {
    id: 115,
    street: "Meadow Vale",
    number: "3",
    city: "Chicago",
    district: "Waywood",
    state: "IL",
  },
  {
    id: 116,
    street: "John Wall",
    number: "611",
    city: "Cincinnati",
    district: "Hagan",
    state: "OH",
  },
  {
    id: 117,
    street: "Petterle",
    number: "3381",
    city: "Baton Rouge",
    district: "Reindahl",
    state: "LA",
  },
  {
    id: 118,
    street: "Northport",
    number: "67",
    city: "Austin",
    district: "Hoepker",
    state: "TX",
  },
  {
    id: 119,
    street: "Mallard",
    number: "74714",
    city: "Erie",
    district: "Veith",
    state: "PA",
  },
  {
    id: 120,
    street: "Coleman",
    number: "1",
    city: "Dayton",
    district: "Warbler",
    state: "OH",
  },
  {
    id: 121,
    street: "Northfield",
    number: "5303",
    city: "Corpus Christi",
    district: "Cascade",
    state: "TX",
  },
  {
    id: 122,
    street: "Sunfield",
    number: "1",
    city: "Los Angeles",
    district: "Crownhardt",
    state: "CA",
  },
  {
    id: 123,
    street: "Beilfuss",
    number: "3312",
    city: "Fort Lauderdale",
    district: "Fremont",
    state: "FL",
  },
  {
    id: 124,
    street: "Russell",
    number: "0",
    city: "Detroit",
    district: "Warrior",
    state: "MI",
  },
  {
    id: 125,
    street: "Oriole",
    number: "20",
    city: "Huntington",
    district: "Crescent Oaks",
    state: "WV",
  },
  {
    id: 126,
    street: "Continental",
    number: "3926",
    city: "Corpus Christi",
    district: "Hoepker",
    state: "TX",
  },
  {
    id: 127,
    street: "Moulton",
    number: "95129",
    city: "Terre Haute",
    district: "Tennyson",
    state: "IN",
  },
  {
    id: 128,
    street: "Maple Wood",
    number: "72430",
    city: "Escondido",
    district: "Graceland",
    state: "CA",
  },
  {
    id: 129,
    street: "Truax",
    number: "1",
    city: "El Paso",
    district: "Butternut",
    state: "TX",
  },
  {
    id: 130,
    street: "Manley",
    number: "419",
    city: "Kansas City",
    district: "Chive",
    state: "MO",
  },
  {
    id: 131,
    street: "Mcguire",
    number: "88542",
    city: "Manchester",
    district: "Dahle",
    state: "NH",
  },
  {
    id: 132,
    street: "Sloan",
    number: "454",
    city: "Dallas",
    district: "International",
    state: "TX",
  },
  {
    id: 133,
    street: "Fallview",
    number: "09627",
    city: "Philadelphia",
    district: "Granby",
    state: "PA",
  },
  {
    id: 134,
    street: "Marcy",
    number: "7290",
    city: "Miami",
    district: "Emmet",
    state: "FL",
  },
  {
    id: 135,
    street: "Grover",
    number: "2",
    city: "Galveston",
    district: "Comanche",
    state: "TX",
  },
  {
    id: 136,
    street: "Claremont",
    number: "8211",
    city: "Redwood City",
    district: "Rockefeller",
    state: "CA",
  },
  {
    id: 137,
    street: "Sunfield",
    number: "95",
    city: "Hartford",
    district: "Meadow Valley",
    state: "CT",
  },
  {
    id: 138,
    street: "Brickson Park",
    number: "57384",
    city: "El Paso",
    district: "Boyd",
    state: "TX",
  },
  {
    id: 139,
    street: "Kedzie",
    number: "4",
    city: "Cleveland",
    district: "Prairie Rose",
    state: "OH",
  },
  {
    id: 140,
    street: "2nd",
    number: "29",
    city: "Killeen",
    district: "Merry",
    state: "TX",
  },
  {
    id: 141,
    street: "Boyd",
    number: "30001",
    city: "Tulsa",
    district: "Manitowish",
    state: "OK",
  },
  {
    id: 142,
    street: "Victoria",
    number: "60",
    city: "Des Moines",
    district: "Arkansas",
    state: "IA",
  },
  {
    id: 143,
    street: "Hoard",
    number: "27396",
    city: "Alhambra",
    district: "Center",
    state: "CA",
  },
  {
    id: 144,
    street: "Portage",
    number: "7181",
    city: "Lexington",
    district: "Oakridge",
    state: "KY",
  },
  {
    id: 145,
    street: "Iowa",
    number: "8537",
    city: "Pasadena",
    district: "Ludington",
    state: "CA",
  },
  {
    id: 146,
    street: "Dottie",
    number: "915",
    city: "Springfield",
    district: "Schiller",
    state: "OH",
  },
  {
    id: 147,
    street: "Tennessee",
    number: "2",
    city: "Charleston",
    district: "Dakota",
    state: "WV",
  },
  {
    id: 148,
    street: "Lawn",
    number: "2",
    city: "Fresno",
    district: "Messerschmidt",
    state: "CA",
  },
  {
    id: 149,
    street: "Barby",
    number: "66405",
    city: "Jackson",
    district: "Merry",
    state: "MS",
  },
  {
    id: 150,
    street: "Tony",
    number: "099",
    city: "Birmingham",
    district: "Lindbergh",
    state: "AL",
  },
];

export function getAddressById(addressId: number) {
  const address = addresses[addressId];

  return address;
}
