export const queue = [
  { id: 1, patientId: 31, doctorId: 9, appointTime: "09:01", returning: false },
  { id: 2, patientId: 36, doctorId: 9, appointTime: "09:58", returning: true },
  { id: 3, patientId: 42, doctorId: 4, appointTime: "11:14", returning: true },
  { id: 4, patientId: 77, doctorId: 4, appointTime: "09:17", returning: true },
  { id: 5, patientId: 44, doctorId: 4, appointTime: "10:37", returning: false },
  { id: 6, patientId: 72, doctorId: 4, appointTime: "09:32", returning: false },
  { id: 7, patientId: 83, doctorId: 2, appointTime: "11:10", returning: false },
  { id: 8, patientId: 56, doctorId: 10, appointTime: "08:00", returning: true },
  { id: 9, patientId: 77, doctorId: 1, appointTime: "09:02", returning: true },
  { id: 10, patientId: 32, doctorId: 9, appointTime: "11:14", returning: true },
  { id: 11, patientId: 28, doctorId: 3, appointTime: "10:24", returning: true },
  { id: 12, patientId: 10, doctorId: 1, appointTime: "10:50", returning: true },
  { id: 13, patientId: 39, doctorId: 6, appointTime: "09:51", returning: true },
  {
    id: 14,
    patientId: 12,
    doctorId: 7,
    appointTime: "10:43",
    returning: false,
  },
  {
    id: 15,
    patientId: 100,
    doctorId: 10,
    appointTime: "10:54",
    returning: false,
  },
  { id: 16, patientId: 52, doctorId: 5, appointTime: "11:25", returning: true },
  { id: 17, patientId: 20, doctorId: 7, appointTime: "10:00", returning: true },
  {
    id: 18,
    patientId: 88,
    doctorId: 1,
    appointTime: "08:49",
    returning: false,
  },
  { id: 19, patientId: 8, doctorId: 5, appointTime: "08:55", returning: true },
  {
    id: 20,
    patientId: 93,
    doctorId: 3,
    appointTime: "10:32",
    returning: false,
  },
  {
    id: 21,
    patientId: 98,
    doctorId: 10,
    appointTime: "09:00",
    returning: true,
  },
  {
    id: 22,
    patientId: 87,
    doctorId: 3,
    appointTime: "08:54",
    returning: false,
  },
  { id: 23, patientId: 20, doctorId: 8, appointTime: "09:27", returning: true },
  {
    id: 24,
    patientId: 87,
    doctorId: 7,
    appointTime: "11:23",
    returning: false,
  },
  {
    id: 25,
    patientId: 48,
    doctorId: 9,
    appointTime: "08:57",
    returning: false,
  },
  { id: 26, patientId: 49, doctorId: 3, appointTime: "08:42", returning: true },
  {
    id: 27,
    patientId: 25,
    doctorId: 2,
    appointTime: "11:25",
    returning: false,
  },
  {
    id: 28,
    patientId: 92,
    doctorId: 2,
    appointTime: "11:02",
    returning: false,
  },
  {
    id: 29,
    patientId: 27,
    doctorId: 2,
    appointTime: "08:28",
    returning: false,
  },
  {
    id: 30,
    patientId: 59,
    doctorId: 5,
    appointTime: "09:42",
    returning: false,
  },
  { id: 31, patientId: 73, doctorId: 6, appointTime: "11:00", returning: true },
  {
    id: 32,
    patientId: 66,
    doctorId: 6,
    appointTime: "11:05",
    returning: false,
  },
  { id: 33, patientId: 51, doctorId: 2, appointTime: "10:11", returning: true },
  { id: 34, patientId: 27, doctorId: 5, appointTime: "08:03", returning: true },
  {
    id: 35,
    patientId: 77,
    doctorId: 2,
    appointTime: "09:26",
    returning: false,
  },
  {
    id: 36,
    patientId: 16,
    doctorId: 10,
    appointTime: "10:05",
    returning: false,
  },
  { id: 37, patientId: 41, doctorId: 5, appointTime: "09:12", returning: true },
  { id: 38, patientId: 43, doctorId: 1, appointTime: "11:09", returning: true },
  { id: 39, patientId: 75, doctorId: 8, appointTime: "08:55", returning: true },
  {
    id: 40,
    patientId: 38,
    doctorId: 8,
    appointTime: "11:24",
    returning: false,
  },
  {
    id: 41,
    patientId: 32,
    doctorId: 4,
    appointTime: "10:46",
    returning: false,
  },
  { id: 42, patientId: 22, doctorId: 5, appointTime: "10:48", returning: true },
  { id: 43, patientId: 94, doctorId: 8, appointTime: "10:56", returning: true },
  { id: 44, patientId: 9, doctorId: 8, appointTime: "08:03", returning: true },
  { id: 45, patientId: 28, doctorId: 9, appointTime: "08:11", returning: true },
  {
    id: 46,
    patientId: 75,
    doctorId: 9,
    appointTime: "11:20",
    returning: false,
  },
  {
    id: 47,
    patientId: 37,
    doctorId: 2,
    appointTime: "11:15",
    returning: false,
  },
  {
    id: 48,
    patientId: 23,
    doctorId: 10,
    appointTime: "08:55",
    returning: true,
  },
  {
    id: 49,
    patientId: 10,
    doctorId: 2,
    appointTime: "10:03",
    returning: false,
  },
  {
    id: 50,
    patientId: 29,
    doctorId: 1,
    appointTime: "09:16",
    returning: false,
  },
  {
    id: 51,
    patientId: 81,
    doctorId: 3,
    appointTime: "11:20",
    returning: false,
  },
  { id: 52, patientId: 98, doctorId: 1, appointTime: "10:14", returning: true },
  {
    id: 53,
    patientId: 89,
    doctorId: 5,
    appointTime: "08:10",
    returning: false,
  },
  {
    id: 54,
    patientId: 40,
    doctorId: 7,
    appointTime: "09:15",
    returning: false,
  },
  { id: 55, patientId: 54, doctorId: 8, appointTime: "10:55", returning: true },
  { id: 56, patientId: 2, doctorId: 2, appointTime: "10:20", returning: true },
  {
    id: 57,
    patientId: 43,
    doctorId: 4,
    appointTime: "08:57",
    returning: false,
  },
  { id: 58, patientId: 97, doctorId: 3, appointTime: "10:07", returning: true },
  { id: 59, patientId: 30, doctorId: 5, appointTime: "09:51", returning: true },
  {
    id: 60,
    patientId: 31,
    doctorId: 6,
    appointTime: "08:11",
    returning: false,
  },
];

export function getDoctorQueue(doctorId: number) {
  const docQueue = queue.filter((q) => q.doctorId === doctorId);
  return docQueue;
}
